---
apiVersion: v1
kind: Secret
metadata:
  name: example-baremetalhost-secret-no-username
type: Opaque
data:
  username: ""
  password: MWYyZDFlMmU2N2Rm

---
apiVersion: v1
kind: Secret
metadata:
  name: example-baremetalhost-secret-no-password
type: Opaque
data:
  username: YWRtaW4=
  password: ""

---
apiVersion: metalkube.org/v1alpha1
kind: BareMetalHost
metadata:
  name: example-baremetalhost
spec:
  online: true
  bmc:
    address: ipmi://192.168.122.1:6233
    credentialsName: example-baremetalhost-secret-no-password
