kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metalkube-baremetal-operator
  namespace: metalkube
subjects:
- kind: ServiceAccount
  name: metalkube-baremetal-operator
- kind: User
  name: developer
roleRef:
  kind: Role
  name: metalkube-baremetal-operator
  apiGroup: rbac.authorization.k8s.io
